### ISSUE TITLE
Doesn't seem to work if web part is in a subdirectory

### ISSUE THREAD

**Issue by tarioch** [kopach/lockfix#205]
My project setup has the web part in a subdirectory, this doesn't seem to work as I'm getting "Not a git root directory" when running it.

I'm on Windows.

**Comment by yoavain** [comment]
This is the same for monorepo. Wanted to run it on every lock file in a Lerna monorepo, and got this error in each package.
I will try to open a PR for that as well.

**Comment by yoavain** [comment]
Decided to create my own implementation instead.
Just published.
I guess it's a bit unethical to put a link here, but you can search for it

**Comment by kopach** [comment]
Implementation of the current tool depends on `GIT`. It checks changes in repo based on git diff of a repo. If there are integrity related changes (sha512 => sha1) - those got reverted (again using git). So, if you would run `lockfix` in sub-folder of your project - it might affect also your other sub-folders within GIT repo. Because of that - running this command in sub-folders could lead to unexpected results, like fixing also other lock files (not only within sub-folder).

Anyway, added `--force` option to bypass GIT root check. Now available from version  https://github.com/kopach/lockfix/releases/tag/v2.2.0
